{{- range $key, $ns := .Values.NamespaceList }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obby-prequisites-creds-es
  namespace: {{ $ns }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.cluster_secretstore | default "vault-cluster-secretstore-default" }}
  refreshInterval: "10m"
  target:
    name: {{ $.Values.OBBY_REG_NAME_CREDS }}
    creationPolicy: Orphan
    template:
      type: Opaque
      data:
        username: {{ "{{ .registry_obby_username }}" | quote }}
        password: {{ "{{ .registry_obby_password }}" | quote }}
  data:
    - secretKey: registry_obby_username
      remoteRef:
        key: {{ $.Values.OBBY_REG_VAULT_PATH }}
        property: username
    - secretKey: registry_obby_password
      remoteRef:
        key: {{ $.Values.OBBY_REG_VAULT_PATH }}
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obby-prequisites-dockerjsonconfig-es
  namespace: {{ $ns }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.cluster_secretstore | default "vault-cluster-secretstore-default" }}
  refreshInterval: "10m"
  target:
    name: {{ $.Values.OBBY_REG_NAME_DOCKERCFG }}
    creationPolicy: Orphan
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{ "{{ .registry_obby_dockerconfig }}" | quote }}
  data:
    - secretKey: registry_obby_dockerconfig
      remoteRef:
        key: {{ $.Values.OBBY_REG_VAULT_PATH }}
        property: .dockerconfigjson
{{- end -}}

