name: Release Charts

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Update chart version
        run: |
          if [ -f "charts/obby-requirements/Chart.yaml" ]; then
            # Mettre à jour la version du chart pour correspondre au tag
            sed -i "s/^version:.*/version: $VERSION/" charts/obby-requirements/Chart.yaml
            git add charts/obby-requirements/Chart.yaml
            git commit -m "Update chart version to $VERSION" || echo "No changes to commit"
          fi

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.CHART_RELEASER_TOKEN }}"

